# Adding ruff ignores here to avoid a noqa comment in the snippets
# and very doc specific rules in the SDK's pyproject.toml.
extend = "../../sdk/python/pyproject.toml"

lint.ignore = [
    "D1",    # docstrings
    "E501",  # line too long
    "S108",  # probable insecure usage of temporary file or directory
    "S311",  # pseudo-random not safe
    "T201",  # `print` found
    "PLR0913",  # too many arguments
]
