plan:
    module: ./aws/ecr
    package: ./tests
inputs:
    TestConfig.awsConfig.accessKey:
        secret: ENC[AES256_GCM,data:iu6LfQNgGZUVnHVeMRYPrcBtlZk=,iv:U5PLxDKXwJnUDdk1ayFGvvJfWdVqh1PK5ujb20YYPP0=,tag:QyqIJRiR6nE16ZDV0CP7Pw==,type:str]
    TestConfig.awsConfig.secretKey:
        secret: ENC[AES256_GCM,data:Q/W+KH3NEouGt6C5S+KiC43837soYi2Mjb/z5K8rD9gtaNaBjjkJHg==,iv:8nGEzLXd91rF5YBZ/EdQoMN27yrpc0sgm26DEvIuSHM=,tag:/oyKl/vj5MJAm+jZMOOAuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gxwmtwahzwdmrskhf90ppwlnze30lgpm056kuesrxzeuyclrwvpsupwtpk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeEk5MS9nVmFoOVNNOHdE
            WnZCTXBWbW9LL1NJYndCYjhIM2JsNXNEUmxJCkUya0dlZjZ0dGRIM1pVdzg5eWFH
            MVpiaE9PclNudGdUZm5FcytuVDZGTDAKLS0tIEQxWDdteHgzS3JkdmtNTVpxMUh1
            aXlvVWJVSGNTSkVyYmpZbi9nUVJZdmMK6csXZ2RMxFw5DB+Hb2TyhyoZT8c2/z7Y
            Lc9Pe8gb8aUq5Ha+wCybYvY6JWEM5A9XYJKbE7f4borTfGKS72d6pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-07-01T16:38:35Z"
    mac: ENC[AES256_GCM,data:eixHdMaEsb8oHkRwhNxDmHou8Jq/oKEJ3bVlHMXFnoobvtOYPk0Dvvp+VJnhNCCaAUQO3q1BwY+/c/r44cBW3zgefmXlR+9vDgeorXqEB0Uixofx8D9nqRhQddFjiKrJd89O7puKPM9aoIwykx7q8Na5HUNu6UzERWvILaYdnC8=,iv:kt7A48dKz/kHyH09pGIUgLhqpxMBG1vmSCAk+4oxqqw=,tag:EGhIUgU9XhH70cbr/lpeCw==,type:str]
    pgp: []
    encrypted_suffix: secret
    version: 3.7.1
