name: Dagger on Namespace - Remote Engine

on:
  workflow_call:
    inputs:
      function:
        description: "Dagger function"
        type: string
        required: true
      size:
        description: "Runner size - used by the Dagger Engine too"
        type: number
        default: 16
        required: false
      timeout:
        description: "Timeout if not finished after this many minutes"
        type: number
        default: 10
        required: false
      dagger:
        description: "Dagger version"
        type: string
        default: "0.17.1"
        required: false
      ubuntu:
        description: "Ubuntu version"
        type: string
        default: "24.04"
        required: false

jobs:
  remote-dagger-engine:
    if: ${{ github.repository == 'dagger/dagger' }}
    runs-on:
      - nscloud-ubuntu-${{ inputs.ubuntu }}-amd64-${{ inputs.size }}x32
      - namespace-experiments:dagger.integration=enabled;dagger.version=${{ inputs.dagger }}
    timeout-minutes: ${{ inputs.timeout }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Warm up Engine
        run: dagger core version
      - name: ${{ inputs.function }}
        uses: ./.github/actions/call-ci-alt-runner
        with:
          function: ${{ inputs.function }}
          version: v${{ inputs.dagger }}
          dev-engine: ${{ inputs.dev }}
      - name: ${{ inputs.function }} (CACHE TEST)
        uses: ./.github/actions/call-ci-alt-runner
        with:
          function: ${{ inputs.function }}
          version: v${{ inputs.dagger }}
          dev-engine: ${{ inputs.dev }}
