name: Dagger on Depot - Local Engine

on:
  workflow_call:
    inputs:
      function:
        description: "Dagger function"
        type: string
        required: true
      size:
        description: "Runner size"
        type: number
        default: 16
        required: false
      timeout:
        description: "Timeout if not finished after this many minutes"
        type: number
        default: 10
        required: false
      dev:
        description: "Use a development version of Dagger"
        type: string
        default: "false"
        required: false
      ubuntu:
        description: "Ubuntu version"
        type: string
        default: "24.04"
        required: false

jobs:
  local-dagger-engine:
    if: ${{ github.repository == 'dagger/dagger' }}
    runs-on: depot-ubuntu-${{ inputs.ubuntu }}-${{ inputs.size }}
    timeout-minutes: ${{ inputs.timeout }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: ${{ inputs.function }}
        uses: ./.github/actions/call-ci-alt-runner
        with:
          module: github.com/${{ github.repository }}@${{ github.sha }}
          function: ${{ inputs.function }}
          dev-engine: ${{ inputs.dev }}
      - name: ${{ inputs.function }} (CACHE TEST)
        uses: ./.github/actions/call-ci-alt-runner
        with:
          module: github.com/${{ github.repository }}@${{ github.sha }}
          function: ${{ inputs.function }}
          dev-engine: ${{ inputs.dev }}
