# This file was generated. See https://daggerverse.dev/mod/github.com/dagger/dagger/modules/gha
name: Core tests
"on":
    push:
        branches:
            - main
            - releases/**
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
            - ready_for_review
    workflow_dispatch: {}
permissions:
    contents: read
concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true
jobs:
    test-call-and-shell:
        runs-on:
            - ${{ github.repository == 'dagger/dagger' && 'nscloud-ubuntu-24.04-amd64-16x32' || 'ubuntu-24.04' }}
        name: test-call-and-shell
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: exec
              id: exec
              uses: dagger/dagger-for-github@v8.2.0
              with:
                call: test specific --race=true --parallel=16 --run='TestCall|TestShell|TestDaggerCMD'
                cloud-token: dag_dagger_sBIv6DsjNerWvTqt2bSFeigBUqWxp9bhh3ONSSgeFnw
                module: github.com/${{ github.repository }}@${{ github.sha }}
                version: v0.19.4
        timeout-minutes: 30
    test-cgroupsv-2:
        runs-on:
            - ${{ github.repository == 'dagger/dagger' && 'nscloud-ubuntu-24.04-amd64-16x32' || 'ubuntu-24.04' }}
        name: test-cgroupsv2
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: exec
              id: exec
              uses: dagger/dagger-for-github@v8.2.0
              with:
                call: test specific --race=true --parallel=16 --run='TestProvision|TestTelemetry'
                cloud-token: dag_dagger_sBIv6DsjNerWvTqt2bSFeigBUqWxp9bhh3ONSSgeFnw
                module: github.com/${{ github.repository }}@${{ github.sha }}
                version: v0.19.4
        timeout-minutes: 30
    test-cli-engine:
        runs-on:
            - ${{ github.repository == 'dagger/dagger' && 'nscloud-ubuntu-24.04-amd64-16x32' || 'ubuntu-24.04' }}
        name: test-cli-engine
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: exec
              id: exec
              uses: dagger/dagger-for-github@v8.2.0
              with:
                call: test specific --race=true --parallel=16 --run='TestCLI|TestEngine'
                cloud-token: dag_dagger_sBIv6DsjNerWvTqt2bSFeigBUqWxp9bhh3ONSSgeFnw
                module: github.com/${{ github.repository }}@${{ github.sha }}
                version: v0.19.4
        timeout-minutes: 30
    test-client-generator:
        runs-on:
            - ${{ github.repository == 'dagger/dagger' && 'nscloud-ubuntu-24.04-amd64-16x32' || 'ubuntu-24.04' }}
        name: test-client-generator
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: exec
              id: exec
              uses: dagger/dagger-for-github@v8.2.0
              with:
                call: test specific --race=true --parallel=16 --run='TestClientGenerator'
                cloud-token: dag_dagger_sBIv6DsjNerWvTqt2bSFeigBUqWxp9bhh3ONSSgeFnw
                module: github.com/${{ github.repository }}@${{ github.sha }}
                version: v0.19.4
        timeout-minutes: 30
    test-container:
        runs-on:
            - ${{ github.repository == 'dagger/dagger' && 'nscloud-ubuntu-24.04-amd64-16x32' || 'ubuntu-24.04' }}
        name: test-container
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: exec
              id: exec
              uses: dagger/dagger-for-github@v8.2.0
              with:
                call: test specific --race=true --parallel=16 --run='TestContainer|TestDockerfile'
                cloud-token: dag_dagger_sBIv6DsjNerWvTqt2bSFeigBUqWxp9bhh3ONSSgeFnw
                module: github.com/${{ github.repository }}@${{ github.sha }}
                version: v0.19.4
        timeout-minutes: 30
    test-everything-else:
        runs-on:
            - ${{ github.repository == 'dagger/dagger' && 'nscloud-ubuntu-24.04-amd64-32x64' || 'ubuntu-24.04' }}
        name: test-everything-else
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: exec
              id: exec
              uses: dagger/dagger-for-github@v8.2.0
              with:
                call: test specific --race=true --parallel=16 --skip='TestProvision|TestTelemetry|TestModule|TestGo|TestPython|TestTypescript|TestElixir|TestPHP|TestJava|TestContainer|TestDockerfile|TestLLM|TestCLI|TestEngine|TestClientGenerator|TestInterface|TestCall|TestShell|TestDaggerCMD'
                cloud-token: dag_dagger_sBIv6DsjNerWvTqt2bSFeigBUqWxp9bhh3ONSSgeFnw
                module: github.com/${{ github.repository }}@${{ github.sha }}
                version: v0.19.4
        timeout-minutes: 30
    test-interface:
        runs-on:
            - ${{ github.repository == 'dagger/dagger' && 'nscloud-ubuntu-24.04-amd64-16x32' || 'ubuntu-24.04' }}
        name: test-interface
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: exec
              id: exec
              uses: dagger/dagger-for-github@v8.2.0
              with:
                call: test specific --race=true --parallel=16 --run='TestInterface'
                cloud-token: dag_dagger_sBIv6DsjNerWvTqt2bSFeigBUqWxp9bhh3ONSSgeFnw
                module: github.com/${{ github.repository }}@${{ github.sha }}
                version: v0.19.4
        timeout-minutes: 30
    test-llm:
        runs-on:
            - ${{ github.repository == 'dagger/dagger' && 'nscloud-ubuntu-24.04-amd64-16x32' || 'ubuntu-24.04' }}
        name: test-LLM
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: exec
              id: exec
              uses: dagger/dagger-for-github@v8.2.0
              with:
                call: test specific --race=true --parallel=16 --run='TestLLM'
                cloud-token: dag_dagger_sBIv6DsjNerWvTqt2bSFeigBUqWxp9bhh3ONSSgeFnw
                module: github.com/${{ github.repository }}@${{ github.sha }}
                version: v0.19.4
        timeout-minutes: 30
    test-module-runtimes:
        runs-on:
            - ${{ github.repository == 'dagger/dagger' && 'nscloud-ubuntu-24.04-amd64-32x64' || 'ubuntu-24.04' }}
        name: test-module-runtimes
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: exec
              id: exec
              uses: dagger/dagger-for-github@v8.2.0
              with:
                call: test specific --race=true --parallel=16 --run='TestGo|TestPython|TestTypescript|TestElixir|TestPHP|TestJava'
                cloud-token: dag_dagger_sBIv6DsjNerWvTqt2bSFeigBUqWxp9bhh3ONSSgeFnw
                module: github.com/${{ github.repository }}@${{ github.sha }}
                version: v0.19.4
        timeout-minutes: 30
    test-modules:
        runs-on:
            - ${{ github.repository == 'dagger/dagger' && 'nscloud-ubuntu-24.04-amd64-32x64' || 'ubuntu-24.04' }}
        name: test-modules
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: exec
              id: exec
              uses: dagger/dagger-for-github@v8.2.0
              with:
                call: test specific --race=true --parallel=16 --run='TestModule'
                cloud-token: dag_dagger_sBIv6DsjNerWvTqt2bSFeigBUqWxp9bhh3ONSSgeFnw
                module: github.com/${{ github.repository }}@${{ github.sha }}
                version: v0.19.4
        timeout-minutes: 30
