name: Engine & CLI

on:
  push:
    branches: ["main"]
    paths-ignore:
      - docs/**
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths-ignore:
      - docs/**
  # Enable manual trigger for easy debugging
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    uses: ./.github/workflows/_hack_make.yml
    secrets: inherit
    with:
      mage-targets: engine:testrace
      size: "dagger-v0-11-1-16c"

  # Run Engine tests in dev Engine so that we can spot integration failures early
  # Only run a subset of important test cases since we just need to verify basic
  # functionality rather than repeat every test already run in the other targets.
  testdev:
    uses: ./.github/workflows/_hack_make.yml
    secrets: inherit
    with:
      mage-targets: engine:testimportant
      size: dagger-runner-docker-fix
      dev-engine: true

  test-publish-cli:
    uses: ./.github/workflows/_hack_make.yml
    secrets: inherit
    with:
      mage-targets: cli:testpublish

  test-publish-engine:
    uses: ./.github/workflows/_hack_make.yml
    secrets: inherit
    with:
      mage-targets: engine:testpublish

  scan-engine:
    name: "Scan Engine Image for Vulnerabilities"
    uses: ./.github/workflows/_hack_make.yml
    secrets: inherit
    with:
      mage-targets: engine:scan
