name: Publish Helm Chart

on:
  push:
    tags: ["helm/chart/v**"]

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: "${{ github.repository == 'dagger/dagger' && 'dagger-v0-11-6-4c-nvme' || 'ubuntu-latest' }}"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: "helm test"
        uses: ./.github/actions/call
        with:
          function: "helm test"
      - name: "helm test publish"
        uses: ./.github/actions/call
        with:
          function: "helm publish --dry-run=true --tag=main"

  publish:
    # only run this on tag push events, not in PRs
    if: github.event_name == 'push' && github.repository == 'dagger/dagger' && github.ref_type == 'tag'
    needs: test
    runs-on: "${{ github.repository == 'dagger/dagger' && 'dagger-v0-11-6-4c-nvme' || 'ubuntu-latest' }}"
    steps:
      - uses: actions/checkout@v4
      - name: "helm publish"
        uses: ./.github/actions/call
        env:
          RELEASE_DAGGER_CI_TOKEN: ${{ secrets.RELEASE_DAGGER_CI_TOKEN }}
        with:
          function: helm publish --tag=${{ github.ref_name }} --github-token=env:RELEASE_DAGGER_CI_TOKEN
      - name: "notify"
        uses: ./.github/actions/notify
        with:
          message: "☸️ Helm Chart: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}"
          discord-webhook: ${{ secrets.NEW_RELEASE_DISCORD_WEBHOOK }}
