name: "Publish NodeJS SDK"
on:
  push:
    tags: ["sdk/nodejs/v**"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: ./hack/make-prod sdk:nodejs:publish ${{ github.ref_name }}
        env:
          NPM_TOKEN: ${{ secrets.RELEASE_NPM_TOKEN }}
