name: "Publish Python SDK"
on:
  push:
    tags:
      - sdk/python/v**
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: ./hack/make sdk:python:publish ${{ github.ref_name }}
        env:
          PYPI_REPO: ${{ secrets.RELEASE_PYPI_REPO }}
          PYPI_TOKEN: ${{ secrets.RELEASE_PYPI_TOKEN }}
