name: "Publish Python SDK"
on:
  push:
    tags: ["sdk/python/v**"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: "1.21"
      - run: ./hack/make sdk:python:publish ${{ github.ref_name }}
        env:
          PYPI_REPO: ${{ secrets.RELEASE_PYPI_REPO }}
          PYPI_TOKEN: ${{ secrets.RELEASE_PYPI_TOKEN }}
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}

  notify:
    needs: publish
    uses: ./.github/workflows/_new_release_notification.yml
    secrets: inherit
    with:
      message: "üêç Python SDK: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}"
