name: publish-sdk-go
on:
  push:
    branches:
      - main
    tags:
      - sdk/go/**
    paths:
      - "sdk/go/**"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
        # https://github.com/magefile/mage-action
      - uses: magefile/mage-action@v2
        with:
          # ⚠️ This must match our go.mod version
          version: v1.14.0
          args: sdk:go:publish ${{ github.ref_name }}
        env:
          GITHUB_PAT: ${{ secrets.RELEASE_DAGGER_CI_TOKEN }}
