name: Publish Helm Chart
on:
  push:
    tags: ["helm/chart/v**"]

jobs:
  publish:
    # only run this on push events, not in PRs
    if: github.event_name == 'push' && github.repository == 'dagger/dagger'
    uses: ./.github/workflows/_hack_make.yml
    secrets: inherit
    with:
      call: helm publish --tag=${{ github.ref_name }} --github-token=env:RELEASE_DAGGER_CI_TOKEN

  notify:
    needs: publish
    uses: ./.github/workflows/_new_release_notification.yml
    secrets: inherit
    with:
      message: "☸️ Helm Chart: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}"
