name: "Publish PHP SDK"
on:
  push:
    branches: ["main"]
    tags: ["sdk/php/v**"]
jobs:
  publish:
    if: github.repository == 'dagger/dagger'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Install dagger
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=${{ inputs.dagger-version }} BIN_DIR=/usr/local/bin/ sudo -E sh
      - run: ./hack/make sdk:php:publish ${{ github.ref_name }}
        env:
          GITHUB_PAT: ${{ secrets.RELEASE_DAGGER_CI_TOKEN }}
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}

  notify:
    if: github.ref_type == 'tag'
    needs: publish
    uses: ./.github/workflows/_new_release_notification.yml
    secrets: inherit
    with:
      message: "üêò PHP SDK: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}"
