name: "Publish Elixir SDK"
on:
  push:
    tags: ["sdk/elixir/v**"]
jobs:
  publish:
    if: github.repository == 'dagger/dagger'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.22"
      - run: ./hack/make sdk:elixir:publish ${{ github.ref_name }}
        env:
          GITHUB_PAT: ${{ secrets.RELEASE_DAGGER_CI_TOKEN }}
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
