name: "Publish Python SDK"
on:
  push:
    tags: ["sdk/python/v**"]
jobs:
  publish:
    if: github.repository == 'dagger/dagger'
    uses: ./.github/workflows/_hack_make.yml
    secrets: inherit
    with:
      call: sdk python publish --tag="${{ github.ref_name }}" --pypi-repo=env:RELEASE_PYPI_REPO --pypi-token=env:RELEASE_PYPI_TOKEN

  notify:
    needs: publish
    uses: ./.github/workflows/_new_release_notification.yml
    secrets: inherit
    with:
      message: "üêç Python SDK: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}"
