name: "Publish Elixir SDK"
on:
  push:
    tags: ["sdk/elixir/v**"]
jobs:
  publish:
    if: github.repository == 'dagger/dagger'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: "1.21"
      - run: ./hack/make sdk:elixir:publish ${{ github.ref_name }}
        env:
          GITHUB_PAT: ${{ secrets.RELEASE_DAGGER_CI_TOKEN }}
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}

  notify:
    needs: publish
    uses: ./.github/workflows/_new_release_notification.yml
    secrets: inherit
    with:
      message: "ðŸ§ª Elixir SDK: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}"
