name: "Test Universe"

on:
  push:
    branches: [main]
    paths:
      - "**.sh"
      - "**.bash"
      - "**.go"
      - "**.cue"
      - "**.bats"
      - "Makefile"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/test-universe.yml"
      - "!docs/**"

  pull_request:
    branches: [main]
    paths:
      - "**.sh"
      - "**.bash"
      - "**.go"
      - "**.cue"
      - "**.bats"
      - "Makefile"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/test-universe.yml"
      - "!docs/**"

jobs:
  universe-europa-tests:
    name: "Universe Tests - Europa"
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: "Check out"
        uses: actions/checkout@v2

      - name: "Set up Go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: "Install SOPS"
        run: |
          sudo curl -L -o /usr/local/bin/sops https://github.com/mozilla/sops/releases/download/v3.7.1/sops-v3.7.1.linux
          sudo chmod +x /usr/local/bin/sops

      - name: "Expose GitHub Runtime"
        uses: crazy-max/ghaction-github-runtime@v1

      - name: Test
        run: |
          export DAGGER_LOG_FORMAT=plain
          make universe-test

      - name: Print Buildkitd Logs
        if: ${{ failure() }}
        run: |
          docker logs dagger-buildkitd
