name: "Test Unit"

on:
  push:
    branches: [v0.2.x]
    paths:
      - '**.go'
      - 'Makefile'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/test-unit.yml'
  pull_request:
    branches: [v0.2.x]
    paths:
      - '**.go'
      - 'Makefile'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/test-unit.yml'

jobs:
  unit-tests:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Check out"
        uses: actions/checkout@v2

      - name: "Setup Go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Test
        run: |
          export DAGGER_LOG_FORMAT=plain
          make test
